### ISSUE TITLE
[Naver Search API] Naver TODO List

### ISSUE THREAD

**Issue by Alaa-abdulridha** [serpapi/public-roadmap#136]
Moved from: https://github.com/serpapi/SerpApi/issues/2289

---
This list is to improve the Naver Engine API, feel free to pick whatever you want to work on.

**-Improving the parser:**

- [x] Extracting ads results [nexearch, web, news] ~ wherever you find ads results.
- [ ] Extracting Inline Images results in nexearch.
- [x] Add more support to the knowledge graph.

**-New features:**

- [x] Support Naver [Images API](https://search.naver.com/search.naver?where=image&sm=tab_jum&query=elon+musk).
- [ ] Support Naver [View API](https://search.naver.com/search.naver?where=view&sm=tab_jum&query=elon+musk).
- [ ] Support Naver [Shopping API](https://search.shopping.naver.com/search/all?where=all&frm=NVSCTAB&query=elon+musk).
- [ ] Support Naver [Encyclopedia API](https://search.naver.com/search.naver?where=kdic&sm=tab_jum&query=elon+musk).
- [ ] Support Naver [Maps API](https://map.naver.com/v5/search/kfc/place/37721322?placePath=%3Fentry%253Dbmp&c=14134688.3488076,4518373.6724403,15,0,0,0,dh).

Nothing in the lists above is urgent!

If you're a user and you want to scrape any of the above API's you're free to bump this issue.
